### ISSUE TITLE
Teleporter sometimes activates when standing near the south west corner of the pad.

### ISSUE THREAD

**Issue by BLuFeNiX** [BLuFeNiX/TeleportationRunes#13]
Reported in #9. Does not reproduce consistently.

**Comment by BLuFeNiX** [comment]
@zaphiredfox I'm closing this for now since I can't reproduce it. Feel free to add more details or test cases and re-open the issue if needed.

My theory is that the players that experience this have walked onto the center of the teleporter just briefly enough for the periodic checking loop to trigger the teleportation task. Once this starts, walking to the corner of the pad is not far enough away to cancel the teleport.

**Comment by zaphiredfox** [comment]
I've not been able to duplicate this since the fix for #12.  Guessing it was somehow related.
