### ISSUE TITLE
Allow teleporting between worlds

### ISSUE THREAD

**Issue by BLuFeNiX** [BLuFeNiX/TeleportationRunes#15]
The primary issue with doing this is determining cost. Short discussion is in #9.

**Comment by BLuFeNiX** [comment]
@zaphiredfox

Implemented similar to your suggestion. I tested that it works, but not that the cost is sane :)

https://github.com/BLuFeNiX/TeleportationRunes/releases/tag/v2.1.0-beta-4

See [config.yml](https://github.com/BLuFeNiX/TeleportationRunes/blob/master/src/main/resources/config.yml) for formula tweaks.

**Comment by zaphiredfox** [comment]
@BLuFeNiX I'd recommend adding that same "anotherWorld" variable to the teleportation delay formula as well.

**Comment by BLuFeNiX** [comment]
@zaphiredfox it's actually already in there, just not properly documented :) -- I also didn't test it, so let me know if it doesn't work for some reason

**Comment by zaphiredfox** [comment]
@BLuFeNiX Tested.  Working well so far!

**Comment by BLuFeNiX** [comment]
Great to hear, thanks!
