### ISSUE TITLE
Cost not displaying before teleport (1.17.1)

### ISSUE THREAD

**Issue by zaphiredfox** [BLuFeNiX/TeleportationRunes#17]
Just updated to Paper 1.17.1.  Plugin still works, but for some reason the cost message is no longer displaying.  Already tried clearing out the plugin config and db, resetting it, no change.  Also removed all other plugins, no change.

**Comment by BLuFeNiX** [comment]
looks like the API for displaying those messages has changed. I was considering making them a little smaller anyway (like the "sneak to confirm" message when using a scroll).

**Comment by BLuFeNiX** [comment]
fixed in aa430c2009f7fb2053aa279d3132ab7dfa3089c4

**Comment by BLuFeNiX** [comment]
@zaphiredfox Just FYI, I have set up some CI builds, and will try to push a new build for each fix as a pre-release, which can be found on the releases page:

https://github.com/BLuFeNiX/TeleportationRunes/releases

The latest one fixes this bug, as well as #14
