### ISSUE TITLE
Is this plugin still being maintained? 

### ISSUE THREAD

**Issue by xardoniak** [BLuFeNiX/TeleportationRunes#5]
This is one of my favorite plugins, found it recently and loaded it into my 1.16.4 server successfully.
Will this plugin be updated to future versions of Minecraft, if required?

Sorry for logging an issue :)

**Comment by BLuFeNiX** [comment]
Hi @xardoniak,

I'm happy to hear this is still being used. I will eventually pick it back up, but I have no set plans as of yet. I will keep you in mind if some spare time sneaks up on me!

**Comment by BLuFeNiX** [comment]
@xardoniak just wanted to let you know that I've been doing some work on the plugin recently. Hope it's still useful to you!
