### ISSUE TITLE
Runes cross worlds?

### ISSUE THREAD

**Issue by xardoniak** [BLuFeNiX/TeleportationRunes#6]
Hey mate,
We built a sender in the overworld and a receiver in the nether and it did not link. I'm assuming cross-world teleportation doesn't work?

**Comment by BLuFeNiX** [comment]
Hi @xardoniak,

It is currently not allowed, but that was a totally arbitrary decision on my part. I can add a feature for you to allow it in the yaml config. Or you are welcome to make the edit and send a pull request :) -- if not I'll try to do it this weekend.

**Comment by xardoniak** [comment]
Hey BlueFenix,
Thanks for getting back to me!
Unfortunately coding isn't something I have knowledge of!

No stress regarding updating it right now, easy enough to work around it! Will let the players know :)
