### ISSUE TITLE
Suggestions / Requests

### ISSUE THREAD

**Issue by zaphiredfox** [BLuFeNiX/TeleportationRunes#8]
@BLuFeNiX With the plugin working now, I'd like to make a few suggestions / requests if you're open to it.

- YML option to customize the book and scroll recipes.  Since my server is well past end-game, end pearls are readily abundant and easy to acquire.  I'd like the ability to modify the recipe to include components that are a bit more work to acquire (ie: ghast tears) or require more of said materials (ie: eight pearls and a book vs just one).
- YML option to modify the "charge up" time before the teleportation occurs.  Optionally make it a customizable calculation based on distance being travelled (the way you do with cost).
- YML option to disable or change the teleportation effects (specifically the lightning).  I happen to like it so far, but I can also see it being an annoyance to others.  An option to have no sounds / effects, or alternatively use the endermen swoops, upon teleportation would be appreciated.
- Haven't tried yet, but does teleportation work between worlds?  If not, please?  Add a YML configurable 'additional charge' (and additional charge up time) to the calculated teleportation cost.
- Cost calculation, can this use any basic math functions?  Ceiling, floor, absolute value, modulo?
- And just for some OPTIONAL random teleportation shenanigans / player torment... a configurable (distance influenced) random chance the teleport will 'malfunction' and 'drop' you somewhere part way between origin and destination.  Hey, this a faster alternative to nether highway travel, but since magic is involved, use at your own risk, MWUAHAHAHA!!

Thanks for all your work on this!

**Comment by BLuFeNiX** [comment]
@zaphiredfox These are great suggestions. I've considered a couple of these before, but you have some cool new ideas as well! I think these are all doable, and I will try to start working on them after I integrate the FreeBSD branch into master, which shouldn't be too much more work.

As for the cost formula, it's powered by `exp4j`, so it should support all the functions listed [here](https://www.objecthunter.net/exp4j/apidocs/index.html), but I have not tested any of them myself.
